app.py
from flask import Flask
from flask_jsglue import JSGlue
from database.core import engine, _create_database, _drop_database

from routes.home import app as home
from routes.tables import app as tables


app = Flask(__name__, template_folder="./templates",
            static_folder="./static")


app.register_blueprint(home)
app.register_blueprint(tables)

jsglue = JSGlue(app)


if __name__ == "__main__":
    _drop_database()
    app.run()

routes/home.py
from flask import Blueprint, render_template, redirect, url_for
from database.core import _create_database, _drop_database, engine, send_query, count
from sqlalchemy_utils import database_exists
from database.functions import FUNCTIONS_AND_PROCEDURES
from routes.tables import tables

app = Blueprint("home", __name__)

@app.route("/create_database")
def create_database():
    _create_database()
    return redirect(url_for('home.home'))


@app.route("/drop_database")
def drop_database():
    _drop_database()
    return redirect(url_for('home.home'))


@app.route("/clear_database")
def clear_database():
    send_query(FUNCTIONS_AND_PROCEDURES['clear_tables'])
    return redirect(url_for('home.home'))


@app.route("/test_input")
def test_input():
    for test_input in FUNCTIONS_AND_PROCEDURES['test_input']:
        send_query(test_input)
    return redirect(url_for('home.home'))


@app.route("/")
def home():
    return render_template("home.html", database_exists=database_exists(engine.url), tables=tables, count=count)

routes/tables.py
import re
from flask import Blueprint, json, render_template, redirect, url_for, jsonify, request
from database.core import engine, send_query
from sqlalchemy_utils import database_exists
from database.functions import FUNCTIONS_AND_PROCEDURES
import json

app = Blueprint("tables", __name__)


tables = {
    'city': {
        'name': 'city',
        'title': 'Города',
        'const_filename': 'js/tables/city_vars.js'
    },
    'storage': {
        'name': 'storage',
        'title': 'Cклады',
        'const_filename': 'js/tables/storage_vars.js',
    },
    'shelf': {
        'name': 'shelf',
        'title': 'Полки',
        'const_filename': 'js/tables/shelf_vars.js',
    },
    'item': {
        'name': 'item',
        'title': 'Предметы',
        'const_filename': 'js/tables/item_vars.js',
    },
    'owner': {
        'name': 'owner',
        'title': 'Владельцы',
        'const_filename': 'js/tables/owner_vars.js',
    },
}


@app.route("/table_clear/<string:table_name>/")
def table_clear(table_name):
    
    try:
        send_query(
            FUNCTIONS_AND_PROCEDURES[f'clear_table'].format(table_name=table_name))
    except Exception as ex:
        return jsonify(error=str(ex))
    
    return jsonify(ok=True)


@app.route("/search_values/<string:table_name>/")
def search_values(table_name):
    req = request.args.get('request', default='', type=str)
    strict = request.args.get('is_strict', default=False, type=bool)
    
    response = send_query(FUNCTIONS_AND_PROCEDURES['search_values'].format(
        table_name=table_name,
        strict=strict,
        request=req)).fetchone()[0]
    return response if response else '[]'


@app.route("/delete_by_index/<string:table_name>/", methods=["POST"])
def delete_by_index(table_name):
    request_data_json = request.data.decode('utf-8')
    request_data = json.loads(request_data_json)
    
    try:
        send_query(FUNCTIONS_AND_PROCEDURES['delete_by_index'].format(
            table_name=table_name,
            index=request_data['index']))
    except Exception as ex:
        return jsonify(error=str(ex))
    return jsonify(ok=True)


@app.route("/insert_value/", methods=["POST"])
def insert_value():
    request_data_json = request.data.decode('utf-8')
    request_data = json.loads(request_data_json)
    table = request_data.pop('table')
    
    try:
        send_query(FUNCTIONS_AND_PROCEDURES[f'insert_{table}'].format(**request_data))
    except Exception as ex:
        return jsonify(error=str(ex))
    
    return jsonify(ok=True)


@app.route("/delete_by_id/", methods=["POST"])
def delete_by_id():
    request_data_json = request.data.decode('utf-8')
    request_data = json.loads(request_data_json)

    try:
        send_query(
            FUNCTIONS_AND_PROCEDURES[f'delete_by_id'].format(**request_data))
    except Exception as ex:
        return jsonify(error=str(ex))
    
    return jsonify(ok=True)


@app.route("/update_value/", methods=["POST"])
def update_value():
    request_data_json = request.data.decode('utf-8')
    request_data = json.loads(request_data_json)
    table = request_data.pop('table')
    
    try:
        send_query(
            FUNCTIONS_AND_PROCEDURES[f'update_{table}'].format(**request_data))
    except Exception as ex:
        return jsonify(error=str(ex))
    
    return jsonify(ok=True)


@app.route("/table/<string:table_name>/get_values/")
def get_values(table_name):
    response = send_query(FUNCTIONS_AND_PROCEDURES['all_values'].format(table_name=table_name)).fetchone()[0]
    return response if response else '[]'

@app.route("/table/<string:table_name>/")
def table(table_name):
    return render_template("table.html", table=tables[table_name])

settings/__init__.py
from .production import *

try:
    from .local_settings import *
except ImportError:
    pass

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {{ JSGlue.include() }}
  </head>
  <body>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <main class="container">
      <div class="row" id="messages">
      </div>
        {% block content %}{% endblock content %}
    </main>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Дом{% endblock title %}


{% block content %}
  <div class="row text-center">
    <h2 class="col-4 mx-auto my-3">Welcome to STORAGE!</h2>
  </div>
  {% if database_exists %}
  <div class="row my-3">
    {% with 
      drop_database_url = url_for('home.drop_database'),
      clear_database_url = url_for('home.clear_database'),
      test_input_url = url_for('home.test_input')
    %}
    <a name="" id="" class="btn btn-danger col-2 mx-auto" href="{{ drop_database_url }}" role="button">Удалить базу</a>
    <a name="" id="" class="btn btn-danger col-2 mx-auto" href="{{ clear_database_url }}" role="button">Очистить базу</a>
    <a name="" id="" class="btn btn-success col-2 mx-auto" href="{{ test_input_url }}" role="button">Test input</a>
    {% endwith %}
  </div>
  <div class="row my-3">
    {% for table in tables %}
    {% with table_url = url_for('tables.table', table_name=table)  %}
    <a class=" btn btn-light card text-center col-md-2 col-5 mx-auto my-2" href="{{ table_url }}">
      <div class="card-body">
        <h4 class="card-title">{{ tables[table]['title'] }}</h4>
        <p class="card-text">{{ count(table) }}</p>
      </div>
      {% endwith %}
    </a>
    {% endfor %}
  </div>
  {% else %}
  <div class="row">
    {% with 
        create_database_url = url_for('home.create_database')
    %}
    <a name="" id="" class="btn btn-success col-3 mx-auto" href="{{ create_database_url }}" role="button">Создать базу</a>
    {% endwith %}
  </div>
  {% endif %}
{% endblock content %}
  

templates/table.html
{% extends 'base.html' %}

{% block title %}{{ table['title'] }}{% endblock title %}


{% block content %}
<div class="row my-3 text-center">
    <h2 class="">{{ table['title'] }}</h2>
</div>
<div class="row my-3">
    {% with home_url = url_for('home.home') %}
    <a name="" id="" class="btn btn-success col-8 col-md-4 mx-auto" href="{{ home_url }}" role="button">На главную</a>
    {% endwith %}
</div>
<div class="row">
    {% if table['name'] != 'storage' %}
    <div class="col-6 col-md-4 mx-auto">
        <div class="my-2">
            <input type="search" class="form-control" name="" id="search" placeholder="Поиск:">
        </div>
        <div class="form-check my-2">
            <input type="checkbox" class="form-check-input" name="" id="strictSearch">
            <label class="form-check-label" for="strictSearch">Точное совпадение</label>
        </div>
    </div>
    <div class="col-6 col-md-2 mx-auto">
        <div class="row my-2">
            <a name="" id="" class="btn btn-primary col-12" role="button" onclick="update_table(document.getElementById('search').value);">Искать</a>
        </div>
        <div class="row">
            <a name="" id="" class="btn btn-danger col-12" role="button" onclick="delete_by_index();">Удалить</a>
        </div>
    </div>
    {% endif %}
    <a class="btn btn-danger card text-center bg-danger col-12 col-md-5 mx-auto my-3" onclick="clear_table();">
        <div class="card-body">
        <h4 class="card-title">Очистить таблицу</h4>
        </div>
    </a>
</div>
<div class="row my-4">
    <div class="col mx-auto my-4 text-center">
        <table class="table table-striped table-borderless">
            <thead class="thead-default" id="thead">
            </thead>
            <tbody class="table-borderless" id="tbody">
            </tbody>
        </table>
    </div>
</div>

<script src="{{ url_for('static', filename=table['const_filename']) }}"></script>
<script src="{{ url_for('static', filename='js/table.js') }}"></script>

{% endblock content %}